apiVersion: v1
kind: ServiceAccount
metadata:
  name: spinnaker-service-account
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: spinnaker-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- namespace: default
  kind: ServiceAccount
  name: spinnaker-service-account
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hal-deployment
  labels:
    app: hal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hal
  template:
    metadata:
      labels:
        app: hal
    spec:
      serviceAccountName: spinnaker-service-account 
      containers:
      - name: hal
        image: anguda/spinnaker:aws-halyard-1.23.7
        env:
          - name: halver
            value: 1.23.7
          - name: access
            valueFrom:
              secretKeyRef:
                name: spinnaker-aws
                key: aws_access_key_id
          - name: secret
            valueFrom:
              secretKeyRef:
                name: spinnaker-aws
                key: aws_secret_access_key
          - name: buck
            value: anguda-spinnaker
          - name: reg
            value: us-east-1
          - name: jenkins_url
            value: http://jenkins-service.default:8080
          - name: jenkins_user
            value: admin
          - name: HOST_IP
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: ui
            value: "http://$(HOST_IP):31000"
          - name: api
            value: "http://$(HOST_IP):32000"
        ports:
        - containerPort: 8084
        - containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  namespace: spinnaker
  labels:
    app: spin
    cluster: spin-gate
  name: spin-gate-np
spec:
  type: NodePort
  ports:
  - name: http
    port: 8084
    nodePort: 32000
    protocol: TCP
  selector:
    app: spin
    cluster: spin-gate
---
apiVersion: v1
kind: Service
metadata:
  namespace: spinnaker
  labels:
    app: spin
    cluster: spin-deck
  name: spin-deck-np
spec:
  type: NodePort
  ports:
  - name: http
    port: 9000
    nodePort: 31000
    protocol: TCP
  selector:
    app: spin
    cluster: spin-deck
---
